# Generated by Django 4.1.3 on 2023-04-02 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
        migrations.AlterField(
            model_name='categories',
            name='name',
            field=models.CharField(max_length=210),
        ),
        migrations.DeleteModel(
            name='Color',
        ),
    ]
