# Generated by Django 4.1.3 on 2023-04-29 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_order_paid_order_payment_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='additional_info',
        ),
    ]
